### ISSUE TITLE
[BUG]: Compatibility Issue with meta Version 1.11.0 and js Version 0.6.7

### ISSUE THREAD

**Issue by aigima** [Canardoux/flutter_sound#1009]
## Flutter Sound Version : 9.3.3

Title: Compatibility Issue with meta Version 1.11.0 and js Version 0.6.7

Description:

Hello Flutter Sound Team,

First off, thank you for your efforts on Flutter Sound. It's a valuable tool for the Flutter community. I've encountered a compatibility issue when integrating your plugin into my project, which I'd like to bring to your attention.

Issue:
The plugin does not seem to be compatible with meta version 1.11.0 and js version 0.6.7, which are currently pinned by the Flutter SDK and other dependencies in my project. This has led to a version-solving conflict.

Steps to Reproduce:

Flutter SDK Version: Flutter 3.19.1 • channel stable 
Add flutter_sound: ^9.3.3 to the pubspec.yaml.
Run flutter pub get to resolve dependencies.

**Comment by Larpoux** [comment]
@aigima : I am very sorry, this is my fault.
Flutter Sound has not been maintained during the last two years, and is not compatible with the last tools version (gradle, logger, stk, idk, …)
I decided to try to update flutter sound but I encountered many more problems than expected.

you have two possibilities:
- dependent your project to the previous versions 
- Wait until I finish the upgrade (from several hours to a few days)

Really sorry 
I will post something in this thread when completed

**Comment by Larpoux** [comment]
@aigima : 
it seems that the problem you have is because you use "channel stable" and that I use "channel master".

I will fix that in the following few days. In the mean time, you may change your "channel version" .
Please note that I found some bugs in "OpenPlay()", "openRecorder()" and "play fromStream()".
I am also going to fix that also in the next few days.

Sorry for the inconvenience. I will post something into this thread when done.

**Comment by Larpoux** [comment]
@aigima 

OK. This is fixed in Flutter Sound 9.3.6

Please not that I found some minor bugs that I will fix in next release : 

[issue 1010](https://github.com/Canardoux/flutter_sound/issues/1010)
[issue 1011](https://github.com/Canardoux/flutter_sound/issues/1011)
[issue 1011](https://github.com/Canardoux/flutter_sound/issues/1011)

**Comment by Larpoux** [comment]
@aigima 

OK. This is fixed in Flutter Sound 9.3.6

Please not that I found some minor bugs that I will fix in next release : 

[issue 1010](https://github.com/Canardoux/flutter_sound/issues/1010)
[issue 1011](https://github.com/Canardoux/flutter_sound/issues/1011)
[issue 1011](https://github.com/Canardoux/flutter_sound/issues/1011)
