### ISSUE TITLE
[DOC]: Almost duplicate files: guides-codecs.md and guides_codecs.md

### ISSUE THREAD

**Issue by tatsuyafujisaki** [Canardoux/flutter_sound#1079]
These two files are almost identical.
- [doc/pages/guides/guides-codecs.md](https://github.com/Canardoux/flutter_sound/blob/master/doc/pages/guides/guides-codecs.md)
- [doc/pages/guides/guides_codecs.md](https://github.com/Canardoux/flutter_sound/blob/master/doc/pages/guides/guides_codecs.md)

Which one is right?

**Comment by Larpoux** [comment]
I think (but I am not completely sure that the good on is 
- [doc/pages/guides/guides_codecs.md](https://github.com/Canardoux/flutter_sound/blob/master/doc/pages/guides/guides_codecs.md)
I just deleted the other.
Thank you again for your help.

Note: I am going to release 9.11.3 because of [(#1077)](https://github.com/Canardoux/flutter_sound/issues/1077) .

**Comment by tatsuyafujisaki** [comment]
Thank you for your quick action!
