### ISSUE TITLE
[BUG]: using flutter sound 9.6.0

### ISSUE THREAD

**Issue by izmeera2000** [Canardoux/flutter_sound#1129]
cupertino_icons: ^1.0.8
  http: ^0.13.3  
  permission_handler: ^10.2.0  
  flutter_inappwebview: ^6.1.5
  just_audio: ^0.9.31
  web_socket_channel: ^2.1.0
  network_info_plus: ^4.0.0
  shared_preferences: ^2.3.3
  flutter_native_splash: ^2.4.2
  pusher_channels_flutter: ^2.3.0
  flutter_local_notifications: ^18.0.1
  flutter_sound: ^9.0.0
  path_provider: ^2.1.5
  
  
  can  build in debug but on release 
  
  > A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR: C:\wamp64\www\cam2\build\flutter_sound\intermediates\merged_res\release\mergeReleaseResources\values\values.xml:2536: AAPT: error: resource android:attr/lStar not found.

**Comment by joshua1996** [comment]
same problem

**Comment by Larpoux** [comment]
@izmeera2000 , @joshua1996 : 

[See this on StackOverflow](https://stackoverflow.com/questions/69033022/message-error-resource-androidattr-lstar-not-found).
I changed the minSdkVersion to 28 instead of 18 and added : buildToolsVersion "34.0.0"

### 9.17.2

- Android : minSdkVersion 28 // 18 works fine for the player, but the recorder needs at least 24 (was 18) ([#1129](https://github.com/Canardoux/flutter_sound/issues/1129))
- Android : buildToolsVersion "34.0.0" (added) ([#1129](https://github.com/Canardoux/flutter_sound/issues/1129))

Could you try if Flutter Sound 9.17.4 is better ?

**Comment by izmeera2000** [comment]
Ty for helping ,
but I was unable to upgrade to 9.17.4 because pusher_channels_flutter require old dependencies of library .
I will try using another library of  pusher_channels_flutter  until then
