### ISSUE TITLE
flutter_sound and tau_sound status

### ISSUE THREAD

**Issue by tan-yaka** [Canardoux/flutter_sound#867]
@Larpoux  I hope you are well my friend.

Can you give an update on the status of these 2 projects? Should devs be moving to tau_sound or is flutter_sound going to be maintained for the foreseable future? I seem to remember you saying there is a lot of work to be done with tau_sound.

Many thanks.

**Comment by Larpoux** [comment]
Your questions are very interesting and I am sure everybody would like to have the answers. But not easy to answer.

For Tau Sound, the answer is simple : Tau Sound was killed. This abandoned project has been replaced by Flutter Sound 9.x and by a new project, not yet really started : Taudio.

For Flutter Sound, there is a big problem because of the lack of contributors. I try to maintain more or less this project myself , but I spend too much time on this maintenance and I would like to do other things. This lack of mainteners is real problem, and it would be very bad for me if the project die.

For Taudio, I started to work on this project, but the amount of work needed for this project is really important, and everybody left this project, except me. The first version of Taudio will not be before next year (and this is not sure).

We really need one or several mainteners on Flutter Sound
